### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by bsonghao** [LindaWang7/personal-web#2]
.

**Comment by LindaWang7** [comment]
Songhao Bao,

I am writing to you because I believe that I have been subjected to
harassment. Over the past few weeks, you have been trying to communicate
with me, but I must make it clear to you that I do not wish to engage in
any form of conversation with you.

Your behavior has made me feel uncomfortable and troubled, and I believe
that it has crossed the line. Therefore, I am requesting that you
immediately cease all forms of harassment, including but not limited to
following, observing, photographing, sending messages, and making phone
calls. I do not wish to receive any more messages from you or hear your
voice. If you continue to engage in this behavior, I will have to take
further action to protect myself.

I hope that you will respect my decision and stop harassing me as soon as
possible. I do not wish to have any conflict with you over this matter, but
I believe that I must express my position clearly.

Thank you for your understanding and cooperation.

Sincerely,

Linda Wang

**Comment by bsonghao** [comment]
Mrs Wang,

    Thanks for letting me know your true feelings. I am sorry to hear that you feel in that way and my apology to make you feel uncomfortable.

     However, I have to adjust myself. What you claimed is not based on the truth. In fact, I feel being harassed by your friend Amily Wu. The messages that your friend send to me is beyond the fundamental principles of universal morality. I encountered humiliation on my personality, way of life, religious belief and sexual orientation. This is a brute violation of the basic human right. This behaviour is not tolerable in a democratic constitution of Canada. The recordings of the messages that Mrs Amily Wu sent to me provides the solid evidence. 

     I hope you doing well. I would appreciate if you can inform that to your friend. If the harassment  continues, I will take measures to protect myself with the resort of  the law.

Kindly regards
Songhao Bao
